org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.newDsl=false

# Mapbox configuration
MAPBOX_DOWNLOADS_TOKEN=YOUR_MAPBOX_DOWNLOADS_TOKEN
MAPBOX_ACCESS_TOKEN=YOUR_MAPBOX_ACCESS_TOKEN
SDK_REGISTRY_TOKEN=YOUR_SDK_REGISTRY_TOKEN
